### ISSUE TITLE
Week1-assembly-exercise 2

### ISSUE THREAD

**Issue by r00tk1ts** [sYstemk1t/Learn#4]
D888A手滑写错了吧，应该是D888H，另外add al,al之后AX确实是D810H啊，你觉着哪里错了呢？
> add ah,ah	AX = D882H	
add al,6	AX = D888A
add al,al	AX =D810H 	；算错了，没有仔细看，只计算低八位

**Comment by sYstemk1t** [comment]
那个算错了的意思是：我一开始算错了，给自己留下，以后算的。
DA888H，写错了！
