### ISSUE TITLE
Week2-C-Chapter 4-实例代码

### ISSUE THREAD

**Issue by r00tk1ts** [sYstemk1t/Learn#5]
4-1你根本就没编译测试吧？至少你第八行一个笔误`getcahr()`就出卖了你。我已经强调很多次了，写程序最重要的是把它run起来，不要求你的程序多么健壮鲁棒，但你基本的测试用例得过吧，bug得解吧？你这个代码问题太多了，基本的测试都不能通过，把它修正，PLEASE！

4-2是单链表的demo，程序运行大体没问题，可以看出你还是下了功夫的，没有敷衍了事。你初学数据结构，且C语言也仅仅用了两个月，所以我不要求你完全独立完成，但希望你能真的搞懂每个接口函数的代码实现，另外，我的单链表的内存图画好了吗？

**Comment by r00tk1ts** [comment]
课后作业的4-1你也没测试吧？程序逻辑有问题。
另外，Week1的两个issue你还没更正，等你更正了之后我再close。

**Comment by sYstemk1t** [comment]
马上好，我把代码全部添加了注释，费了一些时间。
